### ISSUE TITLE
tsnecuda equivalent for M1 chip

### ISSUE THREAD

**Issue by abinashsinha330** [CannyLab/tsne-cuda#113]
Is it possible to take advantage of M1 chip GPU and Neural Engine ecosystem for running tsne efficiently?

**Comment by DavidMChan** [comment]
It would be possible - but it would require a very different architecture to what we provide in this repository. Since the M1 relies on the metal libraries for code acceleration (and not CUDA), we would have to re-write the core code for this repository to support M1 (which isn't feasible at this time).
