### ISSUE TITLE
Warning gives a moving target number of training points that could not be satisfied

### ISSUE THREAD

**Issue by jimmy-academia** [CannyLab/tsne-cuda#114]
I ran `TSNE(n_components=2, perplexity=15, learning_rate=10).fit_transform(X.cpu())` 
on `X.shape = torch.Size([1024, 16384])`
the warning shows: 
`WARNING clustering 1024 points to 32 centroids: please provide at least 1248 training points`

However, when I increase the size to 
`X.shape = torch.Size([1250, 16384])`
it shows
`WARNING clustering 1250 points to 35 centroids: please provide at least 1365 training points`

What option controls the number of centroids and how to avoid this warning?

**Comment by DavidMChan** [comment]
The number of cells is controlled by the square root of the number of points, however FAISS suggests that you have a certain number of training points per centroid (The default is 39 in FAISS, and I don't think we update this anywhere). This means that unless you have ~1500 points, you'll always get this warning because of the moving target.
