### ISSUE TITLE
Request: Parallelization for multiple GPUs (devices)

### ISSUE THREAD

**Issue by ktamiola** [CannyLab/tsne-cuda#13]
I do know this one might be tricky / difficult, however, a support for multiple GPUs would be fantastic, especially for guys like us, who run things on **NVIDIA DGX-1**.

**Comment by rmrao** [comment]
I think this feature would be awesome but it's unlikely we will be able to implement it. Frankly, getting it to scale well to an arbitrary number of GPUs is probably a major research project in and of itself - as far as I can tell, no one has implemented a multi-GPU version of Barnes-Hut period, much less a version for t-SNE.

There's probably some vaguely hacky things we could do. The simplest I can think of would be to do attractive force computation on one GPU and repulsive force computation on a second GPU. Still, it would be a fair amount of work to implement and debug, and since we definitely wouldn't be able to turn that into a publication it's just not something we can justify working on unfortunately.

@DavidMChan and I have been talking about getting an undergrad to work on additional features like this. If that does happen, then we might be able to actually do some of these things, so fingers crossed that we can do that!

**Comment by DavidMChan** [comment]
As of the latest branch, there's now some default parallelization. There's no memory parallelization, however the model does now use several copies of the GPU index to speed up query performance.
