### ISSUE TITLE
question about performance benchmark in README.md

### ISSUE THREAD

**Issue by overshiki** [CannyLab/tsne-cuda#2]
Hi, 
Great works!
I am wondering, for benchmark calculation of MNIST and CIFAR-10 datasets described in README.md, if it was handled after applying PCA dimension reduction to 2 dim or not? Since BH algorithm only supports doing so. The term "runs on the raw pixels" is a little bit confusing.

Thanks a lot.

**Comment by DavidMChan** [comment]
T-SNE is a non-linear dimensionality reduction method - that is, it is designed to reduce a set of points in dimension N to a lower dimension M < N while preserving some information. T-SNE attempts to preserve "local pairwise distances" and works in two phases:

1. T-SNE computes a pairwise distance matrix/approximation of a pairwise distance matrix in the N dimensional space. It then uses these distances to construct a "neighbor likelihood distribution" P_ij.
2. T-SNE randomly initializes points in the lower M dimensional space. It then performs small updates to these M dimensional points so that the "neighbor likelihood distribution" of the points in the lower dimensional space (We'll call this Q_ij) matches the P_ij distribution.

Computing P_ij happens in the high dimension space. In the case of MNIST and CIFAR-10, we take the high dimensional spaces to be pixel space (784 dimensional in the case of MNIST and 3072 dimensional in the case of CIFAR-10), the RGB values of each individual pixel flattened along a single dimension. We don't use Barnes-Hut to compute P_ij - this is done using FAISS combined with some custom CUDA code. 

Computing Q_ij on the other hand happens in the lower dimensional space. In many cases, the lower dimensional space is 2 or 3 dimensional (since we can readily visualize these dimensions). The computation of Q_ij is where we can use the Barnes-Hut algorithm. Computing Q_ij can be decomposed into two steps, computing an attractive force between the points, and computing the repulsive forces. We use the barnes-hut algorithm to assist in computing the repulsive forces between the points, which depend only on points in the lower (M) dimensional space. Thus, Barnes-Hut can be used to speed up the computation of the embedding when we are embedding into a two or three dimensional space. 

To directly answer your question: No, we do not perform PCA dimensionality reduction to two dimensions. We don't use BH directly in the high dimensional space, but instead use it to assist in computation efficiency when embedding into 2 or 3 dimensional spaces.

For more information, see the Barnes-Hut T-SNE paper by L.J.P. van der Maaten et. al. here: https://lvdmaaten.github.io/publications/papers/JMLR_2014.pdf

or, if you prefer code, the CPU only implementation here:
https://github.com/lvdmaaten/bhtsne/

**Comment by overshiki** [comment]
Oh nice!
Yes, we don't need to apply PCA on such a job, I must have been drunk asking this.
Thank you very much for a kind reply.
Best
