### ISSUE TITLE
Illegal instruction in CUDA8.0

### ISSUE THREAD

**Issue by xiaotingFu** [CannyLab/tsne-cuda#25]
Hi, 
I just installed tsne-cuda used anaconda:

`conda install tsnecuda cuda80 -c cannylab # For CUDA8.0`

My nvcc version is listed below:
`
(tsnecuda) [xfu7@c47 ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
`
However using the following test script, I find some error:
```
>>> from tsnecuda import TSNE
>>> import numpy as np
>>> X = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
>>> X_embedded = TSNE().fit_transform(X)
```

WARNING clustering 4 points to 2 centroids: please provide at least 78 training points
Illegal instruction

Can anyone help me what is the problem?

Thanks a lot,

**Comment by DavidMChan** [comment]
For future reference, this is just a warning when you use very few points in the FAISS library. Because this was designed to be optimal for large numbers of points, when you use smaller sets of points, you are doing more bookkeeping work than is necessary. Nothing is going wrong with the library, it just many not be optimal in terms of performance.
