### ISSUE TITLE
what are the GPU memory requirements?

### ISSUE THREAD

**Issue by arm2arm** [CannyLab/tsne-cuda#28]
the sample with (300000,6) is filling up the whole 12GB of my TitanXP, is it the maximum number of data points what i can use with this setup? or there is some room to optimize that?
thanks Arman
ps
btw it is extremely fast on 300k: 5-10sec

**Comment by DavidMChan** [comment]
Because we don't support paging the computation to system memory - this is the maximum number of points for now. 300,000 points in 6 dimensions is a fair numbers - decreasing the number of nearest neighbors may be able to improve your ability to fit more points, but it might also decrease the quality of your approximation.

**Comment by arm2arm** [comment]
thanks! hopefully in some point you can implement the paging as well:)
