### ISSUE TITLE
Gradient Norm: nan

### ISSUE THREAD

**Issue by cciccole** [CannyLab/tsne-cuda#56]
I noticed that some datasets are causing `Gradient Norm: nan` and causing the algorithm to fail, or at least to produce nonsense results.

I have two test files. One causes the error and one does not. The one that does not is mostly identical to the one that does except it is missing ~1500 rows that were sampled out of it at regular interval.

File 1 (fails):  https://drive.google.com/open?id=12tzAyo9SIt7xcSLn2RWTxc0janATpoZk
File 2 (succeeds):   https://drive.google.com/open?id=1VSGkMl6hPzTmXGVmGa4anMvtRmqc1lSf

Strangely, if I run just the row diff as the input, it succeeds. So I'm not sure what it is about the data in the failure file that causes the failure. I also tried shuffling the rows randomly once and it still failed.

I'm using the current build with the major bug fixes but a small number of commits behind.

Curious to hear if you can repro and hopefully find the issue.

**Comment by DavidMChan** [comment]
I seem to be able to run both of these files on my Titan RTX GPU with the default settings in a clean conda environment without getting NaNs in the gradient magnitudes. 

Can you provide a short script that reproduces the bug from the above files? Also - what GPU/CUDA version are you using?

**Comment by cciccole** [comment]
I'm using CUDA 9 / ubuntu 16.04 / Tesla V100.

Thanks for trying it out. I will get back to you on the repro script and also try a different environment while I'm at it. Can't do it at this very moment.

**Comment by raulmendez** [comment]
Hi there, can anyone tell me what was the solution for this thread? I have the same problem, with "**Avg. Gradient Norm: nan**"

**Comment by DavidMChan** [comment]
This is usually caused by issues with the data itself, often duplicated points in the data, vectors that have magnitude zero, or points in the data that are initialized quite close together. It's hard to say exactly what could cause this without the exact data. There's a lot of approximation that happens in the actual training/eval process, which means that any data that doesn't do well under an approximation scenario can cause troubles for the system. When running in verbose mode, is the average gradient norm 0 at all steps, or is it 0 only at the final stage?
