### ISSUE TITLE
Libfaiss Google Colab

### ISSUE THREAD

**Issue by athammad** [CannyLab/tsne-cuda#59]
Hi, 
I am trying to use tsne-cuda on **Google Colab** but I keep getting the following error.

`libfaiss.so: cannot open shared object file: No such file or directory`

I have tried to follow the instruction in the issue #6 and install from source `Libfaiss` as suggested in this  [answer](https://stackoverflow.com/questions/47967252/installing-faiss-on-google-colaboratory) but even if I do not get any error while running the following commands, I still keep getting the same aforementioned error.

```
!wget  https://anaconda.org/pytorch/faiss-gpu/1.2.1/download/linux-64/faiss-gpu-1.2.1-py36_cuda9.0.176_1.tar.bz2
!tar xvjf faiss-gpu-1.2.1-py36_cuda9.0.176_1.tar.bz2
!cp -r lib/python3.6/site-packages/* /usr/local/lib/python3.6/dist-packages/
!pip install mkl
!pip install tsnecuda
```
Could you please provide a solution?

Cheers

**Comment by rmrao** [comment]
I am not sure what version of `tsnecuda` we have on PyPI but it's almost certainly not the most recent one. We could throw something up there, but pip is pretty annoying in terms of supporting different cuda versions, which is why we haven't kept it up to date.

Instead of installing faiss you could follow the same process to install `tsnecuda` from conda. You can get the binaries directly from anaconda (see [here](https://anaconda.org/CannyLab/tsnecuda/files)). This is probably the best solution.

**Comment by achimkoh** [comment]
https://github.com/CannyLab/tsne-cuda/issues/59#issuecomment-523696509 worked for me in a Colab GPU session; just unpacking the binaries still produces the same error, but setting the LD_LIBRARY_PATH environment variable seems to do the trick.

```
!wget https://anaconda.org/CannyLab/tsnecuda/2.1.0/download/linux-64/tsnecuda-2.1.0-cuda100.tar.bz2
!tar xvjf tsnecuda-2.1.0-cuda100.tar.bz2
!cp -r site-packages/* /usr/local/lib/python3.6/dist-packages/
!export LD_LIBRARY_PATH="/content/lib/" 
```

Regarding the last line: `/content` is the default workdir when you run Colab. If you `cd` somewhere else, change path accordingly.
