### ISSUE TITLE
Support for non-random init

### ISSUE THREAD

**Issue by cciccole** [CannyLab/tsne-cuda#63]
Could we have the option to provide a pre-initialized embedding for optimization instead of needing to start from a random initialization?

It looks like this isn't possible at least from the Python wrapper.

**Comment by rmrao** [comment]
Well... so it turns out that a further look shows that we don't know our own library as well as we thought we did, and this functionality is already present :smile: 

`fit_transform` supports two arguments, your input data `x` and a pre-initialized embedding `y`. So just change 

```python
from tsnecuda import TSNE

X = <my data>
y = <my pre-initialized embedding>

y_prime = TSNE().fit_transform(X, y)
```

No need to update any packages~

**Comment by cciccole** [comment]
Got it, will try it out
