### ISSUE TITLE
Varying numbers of nonzero values in perplexity matrix

### ISSUE THREAD

**Issue by zbjornson** [CannyLab/tsne-cuda#83]
Hello, I'm comparing the RAPIDS CUDA tSNE implementation to this package and maybe found a bug. The number of non-zero values in the symmetrized perplexity matrix varies based on the dataset *values*, whereas I think it should be strictly `n_rows * n_neighbors * n_embedding_dimensions`, aside from rare underflows that flush to zero.

| Dataset Seed | nNeighbors | nRow    | nCol | # non-zero, RAPIDS   | # non-zero, tsne-cuda |
|--------------:|------------:|---------:|------:|----------:|-----------:|
| 1            | 5          | 262144  | 4    | 2,621,440  | 1,564,056   |
| 1            | 10         | 262144  | 4    | 5,242,880  | 3,025,336   |
| 1            | 5          | 262144  | 8    | 2,621,440  | 1,620,540   |
| 1            | 5          | 524288  | 4    | 5,242,880  | 3,126,766   |
| 1            | 5          | 1048576 | 4    | 10,485,760 | 6,248,978   |
| 1            | 90         | 262144  | 4    | 47,185,920 | 25,780,964  |
| 0            | 90         | 262144  | 4    | 47,185,920 | 786,432    |

Do you know if that expectation is correct, and if this is thus a bug?

(PS: The perplexity search with default 1e-4 tolerance also appears to be frequently incomplete. If I log `all_found` after the search loop, it's 0 for the majority of datasets that I've tried, unless I raise the perplexity tolerance way up. More so for datasets that have less structure.)

https://github.com/CannyLab/tsne-cuda/blob/568559b33900982cd18a90195efadea8331fb66a/src/kernels/perplexity_search.cu#L132-L133

**Comment by DavidMChan** [comment]
Thanks for the comment! This is actually due to a nuance in the way that we compute the symmetrization. In RAPIDS, they symmetrize in a "non-symmetric" way, that is, if point A is an approximate nearest neighbor with point B, then it's not necessarily the case that point B is an approximate nearest neighbor with point A.In our algorithm, we actually compute the sparse matrix multiply, with the transpose, which means that you're not actually guaranteed to have exactly K neighbors per point (a point will have at least K neighbors, and then any other additional points that have that point as a neighbor). This actually slows our algorithm down somewhat - and can cause more downstream interactions to be computed. It should, however, be more accurate to the true computation. 

In the code on the dev branch, we take the simpler approach to symmetrization, and thus gain the additional performance benefits from fixing this matrix size.

**Comment by zbjornson** [comment]
Thanks for the fast and helpful reply!

> In our algorithm ... a point will have at least K neighbors, and then any other additional points that have that point as a neighbor

If I understand, this is the opposite of what I'm observing though. Based on the numbers I posted, tsne-cuda ultimately appears to have fewer neighbors (== fewer non-zero values). This manifests as fewer invocations of the attractive forces kernel -- tsne-cuda is significantly faster in large part because of this. Am I misreading?

**Comment by DavidMChan** [comment]
Hmm, you may be right. It's possible that because the matrices are sparse, it's actually multiplying by zeros, and ending up with fewer points than it started with. I'll have to take a look at the code, and check this over.

**Comment by DavidMChan** [comment]
Sorry for the slow replies, I've been absolutely drowning in work the last few weeks. From reading through the code, it looks like the exact opposite of what I have above is true - by symmetrizing by multiplying the matrices, it's removing asymmetric connections between the points. I believe that the code in the dev/ branch doesn't have this effect - so we'll look into releasing that. The build process for anaconda is a bit of a pain though, so I have no clue with my current workload how long it will take.

**Comment by zbjornson** [comment]
No problem on timing, really appreciate you looking into it.  What you described makes sense.

Side thought: exact kNN searches of a vector against itself are already symmetric, right? I know this lib currently uses an IVD index though, and I don't know if those searches are symmetric/commutative.

**Comment by DavidMChan** [comment]
Well, this is resolved in the 3.0.0 release, since we calculate the matrices a bit differently. I'm still not exactly sure what was happening.
